#!/bin/bash

# This is only a simple guide to generate template
# Please install spiff before running this script

set -ex

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
WORK_DIR=$(mktemp -d /tmp/upgrade-manifest.XXXXX)

echo "WORK_DIR: ${WORK_DIR}"
cd ${WORK_DIR}

# get repos
git clone https://github.com/cloudfoundry/cf-release -b v244
git clone https://github.com/cloudfoundry/diego-release -b v0.1486.0

# generate cf template, enable ssh-proxy, and set default backend to diego
cf_template_tmp=$(mktemp)
cf_template="${WORK_DIR}/cf.yml"
spiff merge ${SCRIPT_DIR}/generic-manifest-mask.yml \
            ${WORK_DIR}/cf-release/templates/cf.yml \
            ${SCRIPT_DIR}/cf/cf-infrastructure-azure.yml \
            ${SCRIPT_DIR}/cf/cf-stub.yml \
            ${SCRIPT_DIR}/cf/disable-dea-stub.yml \
            > ${cf_template_tmp}
spiff merge ${SCRIPT_DIR}/generic-manifest-mask.yml \
            ${SCRIPT_DIR}/cf/enable-ssh.yml \
            ${cf_template_tmp} \
            ${SCRIPT_DIR}/cf/default-diego-backend-stub.yml \
            > ${cf_template}

# generate diego template which uses *CF* postgres for bbs database
postgres_stub=$(mktemp)
diego_template="${WORK_DIR}/diego.yml"
spiff  merge ${SCRIPT_DIR}/diego/postgres/diego-sql.yml \
             ${SCRIPT_DIR}/diego/postgres/diego-sql-internal.yml \
             ${cf_template} \
             > ${postgres_stub}
${WORK_DIR}/diego-release/scripts/generate-deployment-manifest \
  -c ${cf_template} \
  -i ${SCRIPT_DIR}/diego/iaas-settings.yml \
  -p ${SCRIPT_DIR}/diego/property-overrides.yml \
  -n ${SCRIPT_DIR}/diego/instance-count-overrides.yml \
  -x \
  -s ${postgres_stub} \
  > ${diego_template}

# merge cf and diego templates
diego_template_tmp=$(mktemp)
cf_diego_template_tmp=$(mktemp)
cat ${diego_template} | sed -e 's/^resource_pools:/resource_pools:\n- <<: (( merge ))/g' | \
                      sed -e 's/^jobs:/jobs:\n- <<: (( merge ))/g' | \
                      sed -e 's/^properties:/properties:\n  <<: (( merge ))/g' | \
                      sed -e 's/^networks:/networks:\n- <<: (( merge ))/g' | \
                      sed -e 's/^releases:/releases:\n- <<: (( merge ))/g' \
                      > ${diego_template_tmp}
spiff merge ${SCRIPT_DIR}/generic-manifest-mask.yml \
            ${diego_template_tmp} \
            ${cf_template} \
            > ${cf_diego_template_tmp}

# workaround for etcd: properties.etcd of cf.yml and diego.yml are not same, move related etcd property to <jobs_name>.properties.etcd
# 1. inject properties.etcd of azure-cf.yml to jobs.etcd_z1.properties
# 2. inject properties.etcd of azure-diego to jobs.database_z1.properties
# 3. set properties.etcd to {}
etcd_properties_from_cf=$(mktemp)
etcd_properties_from_diego=$(mktemp)
multiple_vm_template="${WORK_DIR}/multiple-vm-azure.yml"
spiff merge ${SCRIPT_DIR}/etcd/etcd-properties-from-cf.yml \
            ${SCRIPT_DIR}/etcd/etcd-properties-from-cf-internal.yml \
            ${cf_template} \
            > ${etcd_properties_from_cf}
spiff merge ${SCRIPT_DIR}/etcd/etcd-properties-from-diego.yml \
            ${SCRIPT_DIR}/etcd/etcd-properties-from-diego-internal.yml \
            ${diego_template} \
            > ${etcd_properties_from_diego}
spiff merge ${SCRIPT_DIR}/generic-manifest-mask.yml \
            ${SCRIPT_DIR}/etcd/etcd-jobs.yml \
            ${etcd_properties_from_cf} \
            ${etcd_properties_from_diego} \
            ${cf_diego_template_tmp} \
            > ${multiple_vm_template}

echo "multiple vm template is generated at: ${multiple_vm_template}"
