iaas_settings:
  stemcell:
    name: bosh-azure-hyperv-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties:
    instance_type: Standard_D1_v2
  resource_pool_cloud_properties:
    - name: access_z1
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: brain_z1
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: cc_bridge_z1
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: cell_z1
      cloud_properties:
        instance_type: Standard_D2_v2
    - name: colocated_z1
      cloud_properties:
        instance_type: Standard_D2_v2
    - name: database_z1
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: route_emitter_z1
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: errand
      cloud_properties:
        instance_type: Standard_D1_v2
# z2 & z3 are used for high-available deployments
# You can safely remove them if you run a single-zone deployment
    - name: access_z2
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: brain_z2
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: cc_bridge_z2
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: cell_z2
      cloud_properties:
        instance_type: Standard_D2_v2
    - name: colocated_z2
      cloud_properties:
        instance_type: Standard_D2_v2
    - name: database_z2
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: route_emitter_z2
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: access_z3
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: brain_z3
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: cc_bridge_z3
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: cell_z3
      cloud_properties:
        instance_type: Standard_D2_v2
    - name: colocated_z3
      cloud_properties:
        instance_type: Standard_D2_v2
    - name: database_z3
      cloud_properties:
        instance_type: Standard_D1_v2
    - name: route_emitter_z3
      cloud_properties:
        instance_type: Standard_D1_v2

  subnet_configs:
    - name: diego1
      type: manual
      subnets:
      - cloud_properties:
          security_group: nsg-cf
          subnet_name: CloudFoundry
          virtual_network_name: boshvnet-crp
        dns:
        - 168.63.129.16
        gateway: 10.0.16.1
        range: 10.0.16.0/20
        reserved:
        # reserved by cf (assume cf use range 10.0.16.0/24)
        - 10.0.16.2 - 10.0.16.255
        static: []
# diego2 & diego3 subnets are used for high-available deployments
# Currently Azure only support single zone, so z2 and z3 are not used. 
    - name: diego2
      type: manual
      subnets: (( iaas_settings.subnet_configs.diego1.subnets ))
    - name: diego3
      type: manual
      subnets: (( iaas_settings.subnet_configs.diego1.subnets ))

